In [ ]:
import pandas as pd

linkToFile='https://docs.google.com/spreadsheets/d/e/2PACX-1vSPVJIoDhupNyUpYD65FSHt6kMmF_KaxE2RD6CV1FOMP4vVw7WfKQMqpqo0ieD9vhMAmYP1NpBmw0od/pub?gid=658985149&single=true&output=csv'
dataUN=pd.read_csv(linkToFile)

dataUN

In [ ]:
dataUN.info()

In [38]:
dataUN_new=dataUN.copy()

##Columns

In [39]:
# Deleting unnecesary columns

#empty_columns = dataUN.columns[dataUN.isna().all(axis=0)]
#dataUN_new.drop(columns=empty_columns, inplace=True)

toDrop = ['Back', 'Unnamed: 3', 'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 13']
dataUN_new.drop(columns=toDrop, inplace=True)

dataUN_new

,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...
271,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# Fixing column names

new_columns=dataUN_new.iloc[3]+" "+dataUN_new.iloc[5]
dataUN_new.columns=new_columns

dataUN_new.columns.values[0] = 'Country'

dataUN_new

,Country,Human Development Index (HDI) 2021,Life expectancy at birth 2021,Expected years of schooling 2021,Mean years of schooling 2021,Gross national income (GNI) per capita 2021,GNI per capita rank minus HDI rank 2021,HDI rank 2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...
271,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
dataUN_new.columns.to_list()

['Country',
 'Human Development Index (HDI) 2021',
 'Life expectancy at birth 2021',
 'Expected years of schooling 2021',
 'Mean years of schooling 2021',
 'Gross national income (GNI) per capita 2021',
 'GNI per capita rank minus HDI rank 2021',
 'HDI rank 2020']

In [42]:
dataUN_new.columns=dataUN_new.columns.str.strip()
dataUN_new.columns=dataUN_new.columns.str.replace(r"\s","_",regex=True).str.replace(r"\W","",regex=True)

dataUN_new.columns.to_list()

['Country',
 'Human_Development_Index_HDI_2021',
 'Life_expectancy_at_birth_2021',
 'Expected_years_of_schooling_2021',
 'Mean_years_of_schooling_2021',
 'Gross_national_income_GNI_per_capita_2021',
 'GNI_per_capita_rank_minus_HDI_rank_2021',
 'HDI_rank_2020']

In [43]:
cat=dataUN_new[pd.isnull(dataUN_new.Human_Development_Index_HDI_2021)]

cat.head(18)

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,Human development groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
dataUN_new.loc[7:72,'Human_Dev']=cat.Country[6]
dataUN_new.loc[74:122,'Human_Dev']=cat.Country[73]
dataUN_new.loc[124:167,'Human_Dev']=cat.Country[123]
dataUN_new.loc[169:200,'Human_Dev']=cat.Country[168]
dataUN_new.loc[202:206,'Human_Dev']=cat.Country[201]
dataUN_new.loc[208:214,'Human_Dev']=cat.Country[207]
dataUN_new.loc[216:229,'Human_Dev']=cat.Country[215]

mapper1={cat.Country[6]:1,cat.Country[73]:2,cat.Country[123]:3,cat.Country[168]:4,cat.Country[201]:5.1,cat.Country[207]:5.2,cat.Country[215]:5.3}
dataUN_new.Human_Dev.replace(mapper1,inplace=True)

In [45]:
dataUN_new.head(10)

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank,NaN
4,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN,NaN
5,NaN,2021,2021,2021,2021,2021,2021,2020,NaN
6,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Switzerland,962,84.0,16.5,13.9,"66,933",5,3,1.0
8,Norway,961,83.2,18.2,13.0,"64,660",6,1,1.0
9,Iceland,959,82.7,19.2,13.8,"55,782",11,2,1.0

##Filas

In [ ]:
# Deleting unnecesary rows
dataUN_new.drop(range(7), inplace=True)

# Reseting the indexes
dataUN_new=dataUN_new.reset_index(drop=True)

dataUN_new

In [48]:
#Checking the indexes with NaN in the column 'Life_expectancy_at_birth_2021?

dataUN_new[pd.isnull(dataUN_new.Life_expectancy_at_birth_2021)].index
dataUN_new.drop(dataUN_new[pd.isnull(dataUN_new.Life_expectancy_at_birth_2021)].index,inplace=True)

dataUN_new=dataUN_new.reset_index(drop=True)

dataUN_new

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
0,Switzerland,962,84.0,16.5,13.9,"66,933",5,3,1.0
1,Norway,961,83.2,18.2,13.0,"64,660",6,1,1.0
2,Iceland,959,82.7,19.2,13.8,"55,782",11,2,1.0
3,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4,1.0
4,Australia,951,84.5,21.1,12.7,"49,238",18,5,1.0
...,...,...,...,...,...,...,...,...,...
205,Sub-Saharan Africa,547,60.1,10.3,6.0,"3,699",—,—,5.3
206,Least developed countries,540,64.2,10.2,5.2,"2,881",—,—,5.3
207,Small island developing states,730,70.3,12.4,9.1,"16,782",—,—,5.3
208,Organisation for Economic Co-operation and Dev...,899,79.0,16.5,12.3,"45,087",—,—,5.3
209,World,732,71.4,12.8,8.6,"16,752",—,—,5.3

In [ ]:
dataUN_2=dataUN_new.copy()

# complete data
#dataUN_2=dataUN_2[~dataUN_2.isna().any(axis=1)].reset_index(drop=True)

dataUN_2

In [49]:
#Datos

def noSpaces(x,errors='coerce'):
  x=x.str.strip()
  return x

dataUN_new.iloc[:,range(0,8)]=dataUN_new.iloc[:,range(0,8)].apply(noSpaces)

In [51]:
#Símbolos

a=set(dataUN_new.Human_Development_Index_HDI_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
b=set(dataUN_new.Life_expectancy_at_birth_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
c=set(dataUN_new.Expected_years_of_schooling_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
d=set(dataUN_new.Mean_years_of_schooling_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
e=set(dataUN_new.Gross_national_income_GNI_per_capita_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
f=set(dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021.str.extractall('(\W)').loc[:,0].to_list())-set('.')
g=set(dataUN_new.HDI_rank_2020.str.extractall('(\W)').loc[:,0].to_list())-set('.')
a,b,c,d,e,f,g

(set(), set(), set(), set(), {','}, {'-', '—'}, {'—'})

In [52]:
dataUN_new.Gross_national_income_GNI_per_capita_2021=dataUN_new.Gross_national_income_GNI_per_capita_2021.str.replace(',','')
dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021=dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021.str.extract(pat=r'(^-\d+$|\d+)')
dataUN_new.HDI_rank_2020=dataUN_new.HDI_rank_2020.str.extract(pat=r'(^\w+)')

In [53]:
dataUN_new[dataUN_new.Human_Development_Index_HDI_2021.str.contains(pat=r'\W')]

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
191,Korea (Democratic People's Rep. of),..,73.3,10.8,..,..,NaN,NaN,5.1
192,Monaco,..,85.9,..,..,..,NaN,NaN,5.1
193,Nauru,..,63.6,11.7,..,17730,NaN,NaN,5.1
194,Somalia,..,55.3,..,..,1018,NaN,NaN,5.1

In [54]:
dataUN_new.Human_Development_Index_HDI_2021=dataUN_new.Human_Development_Index_HDI_2021.str.extract(pat='(\d+)')
dataUN_new.Expected_years_of_schooling_2021=dataUN_new.Expected_years_of_schooling_2021.str.extract(pat='(\d+.\d+)')
dataUN_new.Mean_years_of_schooling_2021=dataUN_new.Mean_years_of_schooling_2021.str.extract(pat='(\d+.\d+)')
dataUN_new.Gross_national_income_GNI_per_capita_2021=dataUN_new.Gross_national_income_GNI_per_capita_2021.str.extract(pat='(\d+)')

##A

In [57]:
dataUN_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 9 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    210 non-null    object
 1   Human_Development_Index_HDI_2021           206 non-null    object
 2   Life_expectancy_at_birth_2021              210 non-null    object
 3   Expected_years_of_schooling_2021           208 non-null    object
 4   Mean_years_of_schooling_2021               206 non-null    object
 5   Gross_national_income_GNI_per_capita_2021  208 non-null    object
 6   GNI_per_capita_rank_minus_HDI_rank_2021    191 non-null    object
 7   HDI_rank_2020                              191 non-null    object
 8   Human_Dev                                  210 non-null    float64
dtypes: float64(1), object(8)
memory usage: 14.9+ KB

In [58]:
dataUN_new[dataUN_new.duplicated(subset='Country')]

Empty DataFrame
Columns: [Country, Human_Development_Index_HDI_2021, Life_expectancy_at_birth_2021, Expected_years_of_schooling_2021, Mean_years_of_schooling_2021, Gross_national_income_GNI_per_capita_2021, GNI_per_capita_rank_minus_HDI_rank_2021, HDI_rank_2020, Human_Dev]
Index: []

In [59]:
dataUN_new[dataUN_new.Country.str.contains(r'[^\w\s]')]

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
3,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,62607,6,4,1.0
19,Korea (Republic of),925,83.7,16.5,12.5,44501,9,20,1.0
75,Iran (Islamic Republic of),774,73.9,14.6,10.6,13001,15,77,2.0
80,Moldova (Republic of),767,68.8,14.4,11.8,14875,-1,81,2.0
105,"Palestine, State of",715,73.5,13.4,9.9,6583,21,109,2.0
117,Bolivia (Plurinational State of),692,63.6,14.9,9.8,8111,0,119,3.0
119,Venezuela (Bolivarian Republic of),691,70.6,12.8,11.1,4811,20,118,3.0
133,Micronesia (Federated States of),628,70.7,11.5,7.8,3696,22,136,3.0
139,Lao People's Democratic Republic,607,68.1,10.1,5.4,7700,-18,142,3.0
140,Timor-Leste,607,67.7,12.6,5.4,4461,7,140,3.0
143,Eswatini (Kingdom of),597,57.1,13.7,5.6,7679,-21,141,3.0
158,Côte d'Ivoire,550,58.6,10.7,5.2,5217,-22,159,3.0
159,Tanzania (United Republic of),549,66.2,9.2,6.4,2664,7,160,4.0
176,Guinea-Bissau,483,59.7,10.6,3.6,1908,0,177,4.0
178,Congo (Democratic Republic of the),479,59.2,9.8,7.0,1076,9,180,4.0
191,Korea (Democratic People's Rep. of),NaN,73.3,10.8,NaN,NaN,NaN,NaN,5.1
205,Sub-Saharan Africa,547,60.1,10.3,6.0,3699,NaN,NaN,5.3
208,Organisation for Economic Co-operation and Dev...,899,79.0,16.5,12.3,45087,NaN,NaN,5.3

In [60]:
dataUN_new[dataUN_new.Country.str.contains(r"\w*[\u00C0-\u01DA']\w*")]

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
47,Türkiye,838,76.0,18.3,8.6,31033,-3,48,1.0
139,Lao People's Democratic Republic,607,68.1,10.1,5.4,7700,-18,142,3.0
158,Côte d'Ivoire,550,58.6,10.7,5.2,5217,-22,159,3.0
191,Korea (Democratic People's Rep. of),NaN,73.3,10.8,NaN,NaN,NaN,NaN,5.1

In [61]:
pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 5.1 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8

In [62]:
from unidecode import unidecode

dataUN_new['Country']=dataUN_new.Country.apply(unidecode)

In [63]:
dataUN_new['Country']=dataUN_new.Country.str.upper()

In [64]:
def symbols(x,errors='ignore'):
  x=x.str.contains(r'\D\.')
  return x

In [65]:
dataUN_new.head(1)

,Country,Human_Development_Index_HDI_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_2021,Mean_years_of_schooling_2021,Gross_national_income_GNI_per_capita_2021,GNI_per_capita_rank_minus_HDI_rank_2021,HDI_rank_2020,Human_Dev
0,SWITZERLAND,962,84.0,16.5,13.9,66933,5,3,1.0

In [66]:
symbols(dataUN_new.Human_Development_Index_HDI_2021).value_counts()

Human_Development_Index_HDI_2021
False    206
Name: count, dtype: int64

In [67]:
symbols(dataUN_new.Life_expectancy_at_birth_2021).value_counts()

Life_expectancy_at_birth_2021
False    210
Name: count, dtype: int64

In [68]:
symbols(dataUN_new.Expected_years_of_schooling_2021).value_counts()

Expected_years_of_schooling_2021
False    208
Name: count, dtype: int64

In [69]:
symbols(dataUN_new.Mean_years_of_schooling_2021).value_counts()

Mean_years_of_schooling_2021
False    206
Name: count, dtype: int64

In [70]:
symbols(dataUN_new.Gross_national_income_GNI_per_capita_2021).value_counts()

Gross_national_income_GNI_per_capita_2021
False    208
Name: count, dtype: int64

In [71]:
symbols(dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021).value_counts()

GNI_per_capita_rank_minus_HDI_rank_2021
False    191
Name: count, dtype: int64

In [72]:
symbols(dataUN_new.HDI_rank_2020).value_counts()

HDI_rank_2020
False    191
Name: count, dtype: int64

In [73]:
dataUN_new.Human_Development_Index_HDI_2021 = pd.to_numeric(dataUN_new.Human_Development_Index_HDI_2021,errors='coerce')
dataUN_new.Life_expectancy_at_birth_2021 = pd.to_numeric(dataUN_new.Life_expectancy_at_birth_2021,errors='coerce')
dataUN_new.Expected_years_of_schooling_2021 = pd.to_numeric(dataUN_new.Expected_years_of_schooling_2021,errors='coerce')
dataUN_new.Mean_years_of_schooling_2021 = pd.to_numeric(dataUN_new.Mean_years_of_schooling_2021,errors='coerce')
dataUN_new.Gross_national_income_GNI_per_capita_2021 = pd.to_numeric(dataUN_new.Gross_national_income_GNI_per_capita_2021,errors='coerce')
dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021 = pd.to_numeric(dataUN_new.GNI_per_capita_rank_minus_HDI_rank_2021,errors='coerce')
dataUN_new.HDI_rank_2020 = pd.to_numeric(dataUN_new.HDI_rank_2020,errors='coerce')

In [75]:
dataUN_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 9 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    210 non-null    object
 1   Human_Development_Index_HDI_2021           206 non-null    float64
 2   Life_expectancy_at_birth_2021              210 non-null    float64
 3   Expected_years_of_schooling_2021           208 non-null    float64
 4   Mean_years_of_schooling_2021               206 non-null    float64
 5   Gross_national_income_GNI_per_capita_2021  208 non-null    float64
 6   GNI_per_capita_rank_minus_HDI_rank_2021    191 non-null    float64
 7   HDI_rank_2020                              191 non-null    float64
 8   Human_Dev                                  210 non-null    float64
dtypes: float64(8), object(1)
memory usage: 14.9+ KB